version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/js-sdk"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/mobile-app"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
